name: AlwaysDay
main: FaizDev\AlwaysDay\Loader
version: 1.2.1
authors: Faizx511x
api:
- 4.0.0
mcpe-protocol:
- 471
- 475
- 486
website: https://github.com/Faizx511x
description: "Plugin That Makes All Worlds Day Time."
